# Services層84キーの en/zh-Hans 翻訳マージ (1回限り)
import json
import os

TOOLS = os.path.dirname(os.path.abspath(__file__))

en = {
"SvcDownloadManager_D001": "Skipped: external video DL is off", "SvcDownloadManager_D002": "Failed to fetch video info",
"SvcDownloadManager_D003": "Download failed", "SvcDownloadManager_D004": "External video download failed",
"SvcDownloadManager_D005": "Refreshing video info: {0}", "SvcDownloadManager_D006": "Title fetched: {0}",
"SvcDownloadManager_D007": "Fetch failed: {0}", "SvcDownloadManager_D008": "Error: {0}",
"SvcDownloadManager_D009": "{0} is already registered", "SvcDownloadManager_D010": "{0} is queued for adding",
"SvcDownloadManager_D011": "Cannot accept channel addition: {0}", "SvcDownloadManager_D012": "Channel addition queued: {0}",
"SvcDownloadManager_D013": "Channel addition failed: {0}", "SvcDownloadManager_D014": "New video check: {0} channels queued",
"SvcDownloadManager_D015": "add", "SvcDownloadManager_D016": "check",
"SvcDownloadManager_D017": "Fetching video list of {0}... ({1})", "SvcDownloadManager_D018": "Channel \"{0}\" added ({1} videos)",
"SvcDownloadManager_D019": "{0}: {1} videos / {2} new", "SvcDownloadManager_D020": "{0} fetch timed out, will retry later ({1}/{2})",
"SvcDownloadManager_D021": "Failed to fetch {0} (timed out)", "SvcDownloadManager_D022": "Fetch failed: {0}",
"SvcDownloadManager_D023": "Fetching video info... (site={0})", "SvcDownloadManager_D024": "Error: {0}",
"SvcDownloadManager_D025": "Reusing existing file: {0}", "SvcDownloadManager_D026": "Migration started: {0} files",
"SvcDownloadManager_D027": "Fetching via API ({0}/{1}): {2}",
"SvcDownloadManager_D028": "Done: tagged {0} / {1} (skipped {2}, failed {3})",
"SvcDownloadManager_D029": "Processing: {0}/{1} (tagged {2}, skipped {3}, failed {4})",
"SvcDownloadManager_D030": "Thumbnail backfill started: {0} videos", "SvcDownloadManager_D031": "Fetching via API ({0}/{1}): {2}",
"SvcDownloadManager_D032": "Processing: {0}/{1} (URLs {2}, thumbs {3}, failed {4})",
"SvcDownloadManager_D033": "Done: URLs {0} / thumbs {1} / failed {2} (total {3})",
"SvcDownloadManager_D034": "Starting...", "SvcDownloadManager_D035": "Done: URLs {0} / thumbs {1} / failed {2} (total {3})",
"SvcDownloadManager_D036": "Aborted", "SvcDownloadManager_D037": "Error: {0}",
"SvcDownloadManager_D038": "Tag migration", "SvcDownloadManager_D039": "Login required",
"SvcDownloadManager_D040": "Done: tagged {0} / skipped {1} / failed {2} (total {3})", "SvcDownloadManager_D041": "Error: {0}",
"SvcIwaraApiService_D001": "Fetching video list of {0}...", "SvcIwaraApiService_D002": "Failed to run the Python script",
"SvcIwaraApiService_D003": "Error: {0}", "SvcIwaraApiService_D004": "Fetched {0} videos",
"SvcIwaraApiService_D005": "Downloading: {0}", "SvcIwaraApiService_D006": "Download complete",
"SvcIwaraApiService_D007": "Downloading external video: {0}", "SvcIwaraApiService_D008": "External video download complete",
"SvcIwaraApiService_D009": "Running setup...", "SvcIwaraApiService_D010": "Setup complete",
"SvcIwaraApiService_D011": "Setup failed (see the log for details)",
"SvcNotificationService_D001": "Download complete", "SvcNotificationService_D002": "New videos found",
"SvcNotificationService_D003": "Found {1} new videos from {0}", "SvcNotificationService_D004": "Download error",
"SvcEnvironmentSetupService_D001": "Downloading Python embeddable...", "SvcEnvironmentSetupService_D002": "Python DL {0}MB / {1}MB",
"SvcEnvironmentSetupService_D003": "Extracting Python...", "SvcEnvironmentSetupService_D004": "Adjusting Python config (._pth)...",
"SvcEnvironmentSetupService_D005": "Installing pip...", "SvcEnvironmentSetupService_D006": "pip is already installed",
"SvcEnvironmentSetupService_D007": "Downloading get-pip.py...", "SvcEnvironmentSetupService_D008": "Running pip install...",
"SvcEnvironmentSetupService_D009": "Installing {0}...", "SvcEnvironmentSetupService_D010": "Verifying {0}...",
"SvcEnvironmentSetupService_D011": "Checking the specified Python...", "SvcEnvironmentSetupService_D012": "Creating setup marker...",
"SvcEnvironmentSetupService_D013": "Setup complete",
"SvcFileMove_D001": "Not enough free space on the destination drive ({0}).\n\n",
"SvcFileMove_D002": "Required: {0}\n", "SvcFileMove_D003": "Free: {0}\n\n",
"SvcFileMove_D004": "Save folder change aborted.", "SvcFileMove_D005": "Insufficient space",
"SvcFileMove_D006": "{0} will be changed.\n\n", "SvcFileMove_D007": "Existing downloaded files: {0} ({1})\n",
"SvcFileMove_D008": "From: {0}\n", "SvcFileMove_D009": "To: {0}",
"SvcFileMove_D010": "Move these files to the new location?\n",
"SvcFileMove_D011": "(metadata .json files move along with them)\n\n",
"SvcFileMove_D012": "[Yes]    Move files and change the save folder\n",
"SvcFileMove_D013": "[No]     Change the setting only, without moving files\n",
"SvcFileMove_D014": "[Cancel] Do nothing", "SvcFileMove_D015": "Confirm file move",
"Svc_LoginRequired": "Login required. Please log in from the settings screen.",
}

zh = {
"SvcDownloadManager_D001": "跳过：外部视频下载已关闭", "SvcDownloadManager_D002": "获取视频信息失败",
"SvcDownloadManager_D003": "下载失败", "SvcDownloadManager_D004": "外部视频下载失败",
"SvcDownloadManager_D005": "正在重新获取视频信息：{0}", "SvcDownloadManager_D006": "标题获取成功：{0}",
"SvcDownloadManager_D007": "获取失败：{0}", "SvcDownloadManager_D008": "错误：{0}",
"SvcDownloadManager_D009": "{0} 已注册", "SvcDownloadManager_D010": "{0} 正在等待添加",
"SvcDownloadManager_D011": "无法接受频道添加：{0}", "SvcDownloadManager_D012": "频道添加已加入队列：{0}",
"SvcDownloadManager_D013": "频道添加失败：{0}", "SvcDownloadManager_D014": "新视频检查：{0} 个频道已加入队列",
"SvcDownloadManager_D015": "添加", "SvcDownloadManager_D016": "新视频检查",
"SvcDownloadManager_D017": "正在获取 {0} 的视频列表...（{1}）", "SvcDownloadManager_D018": "已添加频道「{0}」（{1} 个视频）",
"SvcDownloadManager_D019": "{0}：{1} 个 / 新 {2} 个", "SvcDownloadManager_D020": "{0} 获取超时，稍后重试（{1}/{2}）",
"SvcDownloadManager_D021": "获取 {0} 失败（超时）", "SvcDownloadManager_D022": "获取失败：{0}",
"SvcDownloadManager_D023": "正在获取视频信息...（site={0}）", "SvcDownloadManager_D024": "错误：{0}",
"SvcDownloadManager_D025": "重用现有文件：{0}", "SvcDownloadManager_D026": "迁移开始：{0} 个文件",
"SvcDownloadManager_D027": "API 获取中（{0}/{1}）：{2}",
"SvcDownloadManager_D028": "完成：已标记 {0} / {1}（跳过 {2}，失败 {3}）",
"SvcDownloadManager_D029": "处理中：{0}/{1}（已标记 {2}，跳过 {3}，失败 {4}）",
"SvcDownloadManager_D030": "缩略图补全开始：{0} 个", "SvcDownloadManager_D031": "API 获取中（{0}/{1}）：{2}",
"SvcDownloadManager_D032": "处理中：{0}/{1}（URL确定 {2}，缩略图 {3}，失败 {4}）",
"SvcDownloadManager_D033": "完成：URL确定 {0} / 缩略图 {1} / 失败 {2}（共 {3} 个）",
"SvcDownloadManager_D034": "开始...", "SvcDownloadManager_D035": "完成：URL确定 {0} / 缩略图 {1} / 失败 {2}（共 {3}）",
"SvcDownloadManager_D036": "已中止", "SvcDownloadManager_D037": "错误：{0}",
"SvcDownloadManager_D038": "标签迁移", "SvcDownloadManager_D039": "需要登录",
"SvcDownloadManager_D040": "完成：标签 {0} / 跳过 {1} / 失败 {2}（共 {3}）", "SvcDownloadManager_D041": "错误：{0}",
"SvcIwaraApiService_D001": "正在获取 {0} 的视频列表...", "SvcIwaraApiService_D002": "Python 脚本执行失败",
"SvcIwaraApiService_D003": "错误：{0}", "SvcIwaraApiService_D004": "已获取 {0} 个视频",
"SvcIwaraApiService_D005": "下载中：{0}", "SvcIwaraApiService_D006": "下载完成",
"SvcIwaraApiService_D007": "外部视频下载中：{0}", "SvcIwaraApiService_D008": "外部视频下载完成",
"SvcIwaraApiService_D009": "正在执行设置...", "SvcIwaraApiService_D010": "设置完成",
"SvcIwaraApiService_D011": "设置失败（详情请查看日志）",
"SvcNotificationService_D001": "下载完成", "SvcNotificationService_D002": "检测到新视频",
"SvcNotificationService_D003": "从 {0} 发现 {1} 个新视频", "SvcNotificationService_D004": "下载错误",
"SvcEnvironmentSetupService_D001": "正在下载 Python embeddable...", "SvcEnvironmentSetupService_D002": "Python 下载中 {0}MB / {1}MB",
"SvcEnvironmentSetupService_D003": "正在解压 Python...", "SvcEnvironmentSetupService_D004": "正在调整 Python 配置 (._pth)...",
"SvcEnvironmentSetupService_D005": "正在安装 pip...", "SvcEnvironmentSetupService_D006": "pip 已安装",
"SvcEnvironmentSetupService_D007": "正在下载 get-pip.py...", "SvcEnvironmentSetupService_D008": "正在执行 pip 安装...",
"SvcEnvironmentSetupService_D009": "正在安装 {0}...", "SvcEnvironmentSetupService_D010": "正在验证 {0}...",
"SvcEnvironmentSetupService_D011": "正在检查指定的 Python...", "SvcEnvironmentSetupService_D012": "正在创建设置标记...",
"SvcEnvironmentSetupService_D013": "设置完成",
"SvcFileMove_D001": "目标驱动器（{0}）可用空间不足。\n\n",
"SvcFileMove_D002": "需要：{0}\n", "SvcFileMove_D003": "可用：{0}\n\n",
"SvcFileMove_D004": "已中止保存位置更改。", "SvcFileMove_D005": "空间不足",
"SvcFileMove_D006": "将更改{0}。\n\n", "SvcFileMove_D007": "现有已下载文件：{0} 个（{1}）\n",
"SvcFileMove_D008": "移动源：{0}\n", "SvcFileMove_D009": "移动目标：{0}",
"SvcFileMove_D010": "将这些文件移动到新位置吗？\n",
"SvcFileMove_D011": "（元数据 .json 也会一起移动）\n\n",
"SvcFileMove_D012": "[是]    移动文件并更改保存位置\n",
"SvcFileMove_D013": "[否]    仅更改设置，不移动文件\n",
"SvcFileMove_D014": "[取消]  不执行任何操作", "SvcFileMove_D015": "文件移动确认",
"Svc_LoginRequired": "需要登录。请从设置画面登录。",
}

ja_extra = {"Svc_LoginRequired": "ログインが必要です。設定画面からログインしてください。"}

for fname, add in (("strings_ja.json", ja_extra), ("strings_en.json", en), ("strings_zh-Hans.json", zh)):
    path = os.path.join(TOOLS, fname)
    d = json.load(open(path, encoding="utf-8"))
    d.update(add)
    json.dump(d, open(path, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print(f"{fname}: +{len(add)} -> {len(d)}")
